<?php

use Livewire\Attributes\Title;
use Livewire\Component;

new #[Title('Inventar')] class extends Component
{
};
?>

<div>
<x-intranet-app-inventar::inventar-layout heading="Inventar" subheading="Anlagenabgang und Standortwechsel melden">
    {{-- Index content is automatically generated by the layout --}}
</x-intranet-app-inventar::inventar-layout>
</div>
